'use strict';

/**
 * Domain knowledge base for the Missing Requirement Inference Engine.
 *
 * Each domain entry:
 * {
 *   keywords:     string[]  — used for domain detection
 *   features:     Rule[]
 *   flows:        Rule[]
 *   roles:        Rule[]
 *   entities:     Rule[]
 *   integrations: Rule[]
 * }
 *
 * Each Rule:
 * { id, name, description, rationale, classification, mvpTier }
 *
 * @type {Record<string, {
 *   keywords: string[],
 *   features: object[],
 *   flows: object[],
 *   roles: object[],
 *   entities: object[],
 *   integrations: object[]
 * }>}
 */
const DOMAIN_RULES = {

  // ── booking ────────────────────────────────────────────────────────────────
  booking: {
    keywords: ['booking', 'appointment', 'schedule', 'reserve', 'barber', 'salon', 'clinic', 'therapist', 'consultant', 'availability'],
    features: [
      {
        id:             'booking_calendar',
        name:           'Booking Calendar',
        description:    'Visual calendar for selecting appointment slots',
        rationale:      'Without a calendar UI users cannot select a date/time — the app has no core function',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'time_slot_management',
        name:           'Time Slot Management',
        description:    'Define available slots per day/provider',
        rationale:      'Core function of any booking system; determines what can be booked',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'booking_confirmation',
        name:           'Booking Confirmation',
        description:    'Confirmation page and email/reference number after booking',
        rationale:      'Users need proof of booking; without this the system is not trustworthy',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'cancellation_rescheduling',
        name:           'Cancellation & Rescheduling',
        description:    'Cancel or reschedule existing bookings',
        rationale:      'Standard user expectation for any booking system',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'provider_profiles',
        name:           'Provider Profiles',
        description:    'Staff/provider bio, photo, and specialties',
        rationale:      'Helps users choose who to book with; common in multi-provider systems',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'booking_reminders',
        name:           'Booking Reminders',
        description:    'Email or SMS reminders before appointment',
        rationale:      'Reduces no-shows; expected in modern booking systems',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
      {
        id:             'waitlist',
        name:           'Waitlist',
        description:    'Join a waitlist for fully-booked slots',
        rationale:      'Maximises bookings when slots are full; domain-specific enhancement',
        classification: 'domain_specific',
        mvpTier:        'could',
      },
    ],
    flows: [
      {
        id:             'flow_book_appointment',
        name:           'Book Appointment Flow',
        description:    'Select service → pick date → pick slot → fill details → confirm',
        rationale:      'This is the primary action in any booking app; must be fully implemented',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_manage_booking',
        name:           'Manage Booking Flow',
        description:    'View, cancel, or reschedule an existing booking',
        rationale:      'Users expect to be able to manage bookings after creation',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'flow_provider_schedule',
        name:           'Provider Schedule Flow',
        description:    'Admin sets working hours and blocks time off',
        rationale:      'Providers must be able to control their availability',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    roles: [
      {
        id:             'role_customer',
        name:           'Customer',
        description:    'End user who books appointments',
        rationale:      'Primary actor in a booking system',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'role_provider',
        name:           'Provider',
        description:    'Staff or service provider who is booked',
        rationale:      'Needed for multi-provider systems; manages own schedule',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'role_admin',
        name:           'Admin',
        description:    'Manages providers, services, and settings',
        rationale:      'Required for platform-level configuration',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    entities: [
      {
        id:             'entity_appointment',
        name:           'Appointment',
        description:    '{id, serviceId, providerId, customerId, dateTime, status, notes}',
        rationale:      'Core data record for any booking system',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_service',
        name:           'Service',
        description:    '{id, name, duration, price, description}',
        rationale:      'Defines what can be booked; required for slot calculation',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_provider',
        name:           'Provider',
        description:    '{id, name, photo, bio, specialties[], workingHours}',
        rationale:      'Needed when multiple staff can be booked independently',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'entity_timeslot',
        name:           'Time Slot',
        description:    '{date, time, providerId, available}',
        rationale:      'Required to show available times on the calendar',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    integrations: [
      {
        id:             'int_email_notifications',
        name:           'Email Notifications',
        description:    'Send booking confirmations via email',
        rationale:      'Users need email confirmation; standard for booking systems',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'int_calendar_export',
        name:           'Calendar Export',
        description:    'Export to Google/Apple Calendar (.ics)',
        rationale:      'Allows users to add appointment to personal calendar',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
      {
        id:             'int_payment_deposit',
        name:           'Payment / Deposit',
        description:    'Collect deposit or full payment at booking time',
        rationale:      'Reduces no-shows; common in premium booking services',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
  },

  // ── marketplace ───────────────────────────────────────────────────────────
  marketplace: {
    keywords: ['marketplace', 'listing', 'sell', 'buyer', 'seller', 'auction', 'bid', 'peer', 'classifieds', 'trade'],
    features: [
      {
        id:             'listing_creation',
        name:           'Listing Creation',
        description:    'Create item listings with title, price, photos, and description',
        rationale:      'Sellers cannot offer anything without a listing creation flow',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'search_filters',
        name:           'Search & Filters',
        description:    'Search by keyword and filter by category, price, and location',
        rationale:      'Buyers cannot find items without search; marketplace is unusable',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'seller_profile',
        name:           'Seller Profile',
        description:    'Seller page with listings, ratings, and response time',
        rationale:      'Builds buyer trust; standard expectation in peer-to-peer marketplaces',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'messaging_system',
        name:           'Messaging System',
        description:    'Buyer-seller messaging within the platform',
        rationale:      'Standard marketplace expectation; needed to negotiate and clarify details',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'review_ratings',
        name:           'Reviews & Ratings',
        description:    'Buyer rates seller after transaction',
        rationale:      'Trust mechanism; critical for peer marketplaces',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'offer_negotiation',
        name:           'Offer / Negotiation',
        description:    'Make or counter offers on listings',
        rationale:      'Common in auction/peer marketplaces; increases transaction success',
        classification: 'domain_specific',
        mvpTier:        'could',
      },
      {
        id:             'saved_searches',
        name:           'Saved Searches',
        description:    'Save search queries with email/push notifications',
        rationale:      'Improves buyer retention when exact item is not yet listed',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    flows: [
      {
        id:             'flow_create_listing',
        name:           'Create Listing Flow',
        description:    'Upload photos → fill details → set price → publish',
        rationale:      'Primary seller action; without it the marketplace has no inventory',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_purchase',
        name:           'Purchase Flow',
        description:    'Find item → view details → contact or buy → complete transaction',
        rationale:      'Primary buyer action; the core transaction loop',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_seller_onboarding',
        name:           'Seller Onboarding Flow',
        description:    'Register as seller, verify identity and payment method',
        rationale:      'Needed before a seller can list; ensures trust and payment routing',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    roles: [
      {
        id:             'role_buyer',
        name:           'Buyer',
        description:    'User who browses and purchases listings',
        rationale:      'One of the two primary actors in any marketplace',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'role_seller',
        name:           'Seller',
        description:    'User who creates and manages listings',
        rationale:      'One of the two primary actors in any marketplace',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'role_moderator',
        name:           'Moderator',
        description:    'Reviews flagged listings and resolves disputes',
        rationale:      'Needed for marketplace trust and safety at scale',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    entities: [
      {
        id:             'entity_listing',
        name:           'Listing',
        description:    '{id, title, price, photos[], category, condition, sellerId, status}',
        rationale:      'Core data record representing an item for sale',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_transaction',
        name:           'Transaction',
        description:    '{id, listingId, buyerId, sellerId, amount, status}',
        rationale:      'Records the exchange of money between buyer and seller',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'entity_review',
        name:           'Review',
        description:    '{id, authorId, targetId, rating, comment}',
        rationale:      'Enables trust-building through seller reputation',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    integrations: [
      {
        id:             'int_payment_escrow',
        name:           'Payment / Escrow',
        description:    'Secure payment processing between buyer and seller',
        rationale:      'Needed to handle money safely in peer-to-peer transactions',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'int_image_hosting',
        name:           'Image Hosting',
        description:    'Store and serve listing photos',
        rationale:      'Listing photos are critical; must be stored reliably',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'int_identity_verification',
        name:           'Identity Verification',
        description:    'Verify seller identity to prevent fraud',
        rationale:      'Increases buyer trust; important for high-value marketplaces',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
  },

  // ── saas ──────────────────────────────────────────────────────────────────
  saas: {
    keywords: ['saas', 'subscription', 'dashboard', 'platform', 'workspace', 'team', 'billing', 'invoice', 'crm', 'software'],
    features: [
      {
        id:             'auth_full',
        name:           'Full Authentication',
        description:    'Sign up, login, password reset, and email verification',
        rationale:      'SaaS products require secure user accounts; no auth means no product',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'subscription_management',
        name:           'Subscription Management',
        description:    'Plans, billing cycle, upgrade and downgrade',
        rationale:      'Core business model for SaaS; without it there is no revenue',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'team_workspaces',
        name:           'Team Workspaces',
        description:    'Invite team members, assign roles, and share data',
        rationale:      'Most SaaS products are used by teams; expected feature',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'usage_analytics',
        name:           'Usage Analytics',
        description:    'Usage metrics, limits, and overage warnings',
        rationale:      'Users need to understand their usage against their plan limits',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'api_access',
        name:           'API Access',
        description:    'API key management for programmatic access',
        rationale:      'Developer-facing SaaS products need API keys for integrations',
        classification: 'domain_specific',
        mvpTier:        'could',
      },
      {
        id:             'audit_log',
        name:           'Audit Log',
        description:    'History of account actions for compliance',
        rationale:      'Required for compliance-sensitive SaaS (HIPAA, SOC2, etc.)',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
      {
        id:             'onboarding_flow',
        name:           'Onboarding Flow',
        description:    'Guided setup wizard for new users',
        rationale:      'Critical for activation; users who do not reach first value churn immediately',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    flows: [
      {
        id:             'flow_signup_onboarding',
        name:           'Signup & Onboarding Flow',
        description:    'Register → verify email → onboarding wizard → reach first value',
        rationale:      'Activation flow; the most critical funnel in any SaaS product',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_subscription_upgrade',
        name:           'Subscription Upgrade Flow',
        description:    'View plans → select plan → pay → unlock features',
        rationale:      'The core monetisation flow; SaaS cannot generate revenue without it',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_team_invite',
        name:           'Team Invite Flow',
        description:    'Send invite → recipient accepts → joins workspace',
        rationale:      'Needed for team collaboration and viral growth',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    roles: [
      {
        id:             'role_owner',
        name:           'Owner',
        description:    'Account owner with billing responsibility',
        rationale:      'Every SaaS account needs a responsible owner for billing and settings',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'role_admin',
        name:           'Admin',
        description:    'Can manage team members and settings',
        rationale:      'Needed to delegate management without sharing billing access',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'role_member',
        name:           'Member',
        description:    'Standard team member with product access',
        rationale:      'Core team role for multi-user workspaces',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'role_viewer',
        name:           'Viewer',
        description:    'Read-only access for stakeholders',
        rationale:      'Useful for sharing dashboards/reports without edit rights',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    entities: [
      {
        id:             'entity_account',
        name:           'Account',
        description:    '{id, name, plan, billingEmail, seats}',
        rationale:      'Organisational unit for a SaaS customer; required for billing',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_subscription',
        name:           'Subscription',
        description:    '{id, accountId, planId, status, renewsAt}',
        rationale:      'Tracks the active plan and billing cycle per account',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_user',
        name:           'User',
        description:    '{id, email, name, role, accountId}',
        rationale:      'Individual user within an account; required for authentication',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
    ],
    integrations: [
      {
        id:             'int_stripe',
        name:           'Stripe',
        description:    'Payment processing and subscription management',
        rationale:      'Industry-standard for SaaS billing; handles recurring payments',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'int_email_transactional',
        name:           'Transactional Email',
        description:    'Welcome, password reset, and invoice emails',
        rationale:      'Required for auth flows and billing communications',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'int_analytics',
        name:           'Product Analytics',
        description:    'User analytics (Mixpanel/Amplitude style)',
        rationale:      'Needed to understand feature adoption and improve product',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
  },

  // ── restaurant ────────────────────────────────────────────────────────────
  restaurant: {
    keywords: ['restaurant', 'menu', 'food', 'order', 'delivery', 'reservation', 'table', 'cuisine', 'chef', 'takeout', 'dine'],
    features: [
      {
        id:             'digital_menu',
        name:           'Digital Menu',
        description:    'Browse menu by category with photos, prices, and descriptions',
        rationale:      'Without a menu the restaurant app has no core content',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'online_ordering',
        name:           'Online Ordering',
        description:    'Add to cart, customise items, and checkout',
        rationale:      'Core revenue-generating feature for restaurant apps',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'table_reservation',
        name:           'Table Reservation',
        description:    'Book a table for dine-in',
        rationale:      'Expected for sit-down restaurants; reduces wait times',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'order_tracking',
        name:           'Order Tracking',
        description:    'Real-time status: received → preparing → ready / out for delivery',
        rationale:      'Customers expect to track their order; reduces support enquiries',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'loyalty_program',
        name:           'Loyalty Program',
        description:    'Points for orders and rewards for repeat customers',
        rationale:      'Drives repeat purchases; common in modern restaurant apps',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
      {
        id:             'special_dietary_filters',
        name:           'Dietary Filters',
        description:    'Filter menu by vegan, gluten-free, allergens, etc.',
        rationale:      'Important for accessibility and regulatory compliance',
        classification: 'domain_specific',
        mvpTier:        'could',
      },
    ],
    flows: [
      {
        id:             'flow_place_order',
        name:           'Place Order Flow',
        description:    'Browse menu → add items → customise → cart → checkout',
        rationale:      'The primary revenue-generating flow in any restaurant app',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_reserve_table',
        name:           'Reserve Table Flow',
        description:    'Select date/time → party size → confirm reservation',
        rationale:      'Core dine-in flow; needed for sit-down restaurant experiences',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'flow_order_tracking',
        name:           'Order Tracking Flow',
        description:    'Receive real-time status updates on order progress',
        rationale:      'Reduces anxiety and support calls; standard modern expectation',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    roles: [
      {
        id:             'role_customer',
        name:           'Customer',
        description:    'End user who orders food or reserves a table',
        rationale:      'Primary actor in any restaurant app',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'role_kitchen_staff',
        name:           'Kitchen Staff',
        description:    'View and update order status in kitchen display',
        rationale:      'Needed to close the order lifecycle loop',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'role_delivery_driver',
        name:           'Delivery Driver',
        description:    'Picks up and delivers orders, updates delivery status',
        rationale:      'Required for delivery-enabled restaurant apps',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    entities: [
      {
        id:             'entity_menu_item',
        name:           'Menu Item',
        description:    '{id, name, price, category, description, photo, modifiers[]}',
        rationale:      'Core content unit of any restaurant app',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_order',
        name:           'Order',
        description:    '{id, items[], total, status, customerId, type(dine-in/delivery/takeout)}',
        rationale:      'Core transaction record for a restaurant',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_reservation',
        name:           'Reservation',
        description:    '{id, dateTime, partySize, customerId, status}',
        rationale:      'Required for table booking functionality',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    integrations: [
      {
        id:             'int_payment_pos',
        name:           'Payment / POS',
        description:    'Process payments online for orders',
        rationale:      'Required to complete any online order transaction',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'int_sms_updates',
        name:           'SMS Updates',
        description:    'SMS order status updates to customers',
        rationale:      'Keeps customers informed without requiring app notifications',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
      {
        id:             'int_maps_delivery',
        name:           'Maps / Delivery',
        description:    'Delivery area map and address lookup',
        rationale:      'Required for delivery apps to validate delivery zones',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
  },

  // ── fitness ───────────────────────────────────────────────────────────────
  fitness: {
    keywords: ['fitness', 'gym', 'workout', 'exercise', 'trainer', 'health', 'wellness', 'yoga', 'strength', 'cardio', 'nutrition'],
    features: [
      {
        id:             'workout_library',
        name:           'Workout Library',
        description:    'Browsable exercise and workout library with instructions',
        rationale:      'Users need a library of exercises to build workouts from',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'workout_logging',
        name:           'Workout Logging',
        description:    'Log sets, reps, weight, and duration per exercise',
        rationale:      'Core value proposition of any fitness tracker',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'progress_tracking',
        name:           'Progress Tracking',
        description:    'Charts for weight, reps, and body metrics over time',
        rationale:      'Primary motivation for users; without it there is no engagement loop',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'workout_plans',
        name:           'Workout Plans',
        description:    'Pre-built or custom multi-week training programs',
        rationale:      'Structured programs increase retention and goal achievement',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'nutrition_tracking',
        name:           'Nutrition Tracking',
        description:    'Log meals, calories, and macros',
        rationale:      'Holistic fitness apps track both exercise and diet',
        classification: 'domain_specific',
        mvpTier:        'could',
      },
      {
        id:             'class_scheduling',
        name:           'Class Scheduling',
        description:    'Book group fitness classes with instructor',
        rationale:      'Required for gym or studio apps with group classes',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'personal_trainer_booking',
        name:           'Personal Trainer Booking',
        description:    'Book 1-on-1 sessions with a personal trainer',
        rationale:      'Premium upsell feature for gyms with personal training services',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    flows: [
      {
        id:             'flow_log_workout',
        name:           'Log Workout Flow',
        description:    'Start workout → log each exercise → finish → view summary',
        rationale:      'Primary daily action in any fitness app',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_view_progress',
        name:           'View Progress Flow',
        description:    'Select metric → view chart → see personal record history',
        rationale:      'Core motivation loop; drives return visits',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_join_class',
        name:           'Join Class Flow',
        description:    'Browse classes → select → book → attend',
        rationale:      'Required for gym/studio apps offering group classes',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    roles: [
      {
        id:             'role_member',
        name:           'Member',
        description:    'Gym or app member who logs workouts',
        rationale:      'Primary user of any fitness app',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'role_trainer',
        name:           'Trainer',
        description:    'Personal trainer or class instructor',
        rationale:      'Needed for apps with guided training or class booking',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'role_admin',
        name:           'Admin',
        description:    'Manages gym settings, classes, and membership',
        rationale:      'Required for gym management applications',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    entities: [
      {
        id:             'entity_workout_session',
        name:           'Workout Session',
        description:    '{id, userId, date, exercises[], duration, notes}',
        rationale:      'Core record of a completed workout',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_exercise',
        name:           'Exercise',
        description:    '{id, name, muscleGroups[], instructions, videoUrl}',
        rationale:      'Building block of the workout library',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_fitness_class',
        name:           'Fitness Class',
        description:    '{id, name, instructorId, schedule, capacity, bookings[]}',
        rationale:      'Required for class scheduling features',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    integrations: [
      {
        id:             'int_wearable_sync',
        name:           'Wearable Sync',
        description:    'Sync with fitness trackers (Fitbit, Apple Health)',
        rationale:      'Popular fitness apps integrate with wearables for automatic logging',
        classification: 'domain_specific',
        mvpTier:        'could',
      },
      {
        id:             'int_video_streaming',
        name:           'Video Streaming',
        description:    'Video demonstrations for exercises',
        rationale:      'Improves exercise instruction quality; expected in modern fitness apps',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
  },

  // ── ecommerce ─────────────────────────────────────────────────────────────
  ecommerce: {
    keywords: ['shop', 'store', 'ecommerce', 'product', 'cart', 'checkout', 'order', 'inventory', 'retail', 'buy', 'purchase'],
    features: [
      {
        id:             'product_catalog',
        name:           'Product Catalog',
        description:    'Product pages with photos, variants, and descriptions',
        rationale:      'Without a catalog buyers have nothing to browse or purchase',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'shopping_cart',
        name:           'Shopping Cart',
        description:    'Add and remove items; persistent cart across sessions',
        rationale:      'Fundamental e-commerce pattern; required before checkout',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'checkout_flow',
        name:           'Checkout Flow',
        description:    'Address, shipping, payment, and order confirmation',
        rationale:      'The revenue-generating step; without it no sales occur',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'order_history',
        name:           'Order History',
        description:    'Past orders with status and details',
        rationale:      'Customers expect to review past purchases and track returns',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'inventory_management',
        name:           'Inventory Management',
        description:    'Stock levels and out-of-stock handling',
        rationale:      'Prevents overselling; required for physical product stores',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'product_search',
        name:           'Product Search',
        description:    'Search and filter by category, price, and rating',
        rationale:      'Essential for stores with more than a handful of products',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'wishlist',
        name:           'Wishlist',
        description:    'Save products for later purchase',
        rationale:      'Increases return visits and conversion rate',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
      {
        id:             'discount_codes',
        name:           'Discount Codes',
        description:    'Promo codes applied at checkout',
        rationale:      'Common marketing tool for e-commerce stores',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    flows: [
      {
        id:             'flow_purchase',
        name:           'Purchase Flow',
        description:    'Browse → product detail → add to cart → checkout → confirmation',
        rationale:      'The complete purchase funnel; the most critical flow in e-commerce',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_track_order',
        name:           'Track Order Flow',
        description:    'Order confirmation → tracking number → delivery status',
        rationale:      'Reduces customer support load; standard post-purchase expectation',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'flow_return_refund',
        name:           'Return & Refund Flow',
        description:    'Initiate return → select reason → refund processed',
        rationale:      'Required for consumer protection compliance; builds trust',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    roles: [
      {
        id:             'role_customer',
        name:           'Customer',
        description:    'End user who browses and buys products',
        rationale:      'Primary actor in any e-commerce application',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'role_store_admin',
        name:           'Store Admin',
        description:    'Manages products, orders, and inventory',
        rationale:      'Required to operate and maintain the store',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    entities: [
      {
        id:             'entity_product',
        name:           'Product',
        description:    '{id, name, price, variants[], stock, photos[], categoryId}',
        rationale:      'Core sellable item in any e-commerce system',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_order',
        name:           'Order',
        description:    '{id, customerId, items[], total, status, shippingAddress}',
        rationale:      'Core transaction record; required for fulfilment and history',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_cart',
        name:           'Cart',
        description:    '{userId/sessionId, items[], updatedAt}',
        rationale:      'Persistent cart state between sessions; reduces abandonment',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
    ],
    integrations: [
      {
        id:             'int_payment_gateway',
        name:           'Payment Gateway',
        description:    'Stripe or PayPal payment processing',
        rationale:      'Required to accept online payments; no checkout without it',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'int_shipping_api',
        name:           'Shipping API',
        description:    'Shipping rates and tracking (USPS/FedEx/UPS)',
        rationale:      'Needed to calculate shipping costs and provide tracking numbers',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'int_email_receipts',
        name:           'Email Receipts',
        description:    'Order confirmation and shipping notification emails',
        rationale:      'Required for legal compliance and customer communication',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
  },

  // ── ai_tool ───────────────────────────────────────────────────────────────
  ai_tool: {
    keywords: ['ai', 'artificial intelligence', 'ml', 'gpt', 'llm', 'model', 'generate', 'prompt', 'chatbot', 'assistant', 'neural'],
    features: [
      {
        id:             'prompt_builder',
        name:           'Prompt Builder',
        description:    'UI for crafting prompts with templates and suggestions',
        rationale:      'The primary input interface for any AI tool; without it users cannot use the product',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'generation_history',
        name:           'Generation History',
        description:    'Save and revisit past generations',
        rationale:      'Users need to reference past outputs; core retention feature',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'output_display',
        name:           'Output Display',
        description:    'Clean display of AI output with copy and export actions',
        rationale:      'The primary output surface; must be readable and actionable',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'usage_quota',
        name:           'Usage Quota',
        description:    'Show remaining credits or tokens and upgrade prompts',
        rationale:      'Required for monetisation; users need to know their limits',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'output_feedback',
        name:           'Output Feedback',
        description:    'Rate or regenerate output; thumbs up/down',
        rationale:      'Improves output quality through feedback; standard AI tool pattern',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'prompt_library',
        name:           'Prompt Library',
        description:    'Community or personal saved prompts',
        rationale:      'Accelerates user onboarding; increases engagement',
        classification: 'domain_specific',
        mvpTier:        'could',
      },
      {
        id:             'model_selection',
        name:           'Model Selection',
        description:    'Choose between different AI models or settings',
        rationale:      'Power users want control over model parameters',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    flows: [
      {
        id:             'flow_generate',
        name:           'Generate Flow',
        description:    'Enter prompt → configure options → generate → view output → save or export',
        rationale:      'The primary value-delivery flow of any AI tool',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_iterate',
        name:           'Iterate Flow',
        description:    'View output → refine prompt → regenerate → compare versions',
        rationale:      'Iteration is central to AI tool usage; improves output quality',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'flow_manage_history',
        name:           'Manage History Flow',
        description:    'Browse past generations → search → reuse prompt',
        rationale:      'Enables users to build on previous work',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    roles: [
      {
        id:             'role_user',
        name:           'User',
        description:    'Standard user who generates AI outputs',
        rationale:      'Primary actor in any AI tool',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'role_power_user',
        name:           'Power User',
        description:    'API access, advanced model settings',
        rationale:      'Developer/advanced segment with programmatic access needs',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    entities: [
      {
        id:             'entity_generation',
        name:           'Generation',
        description:    '{id, userId, prompt, output, model, createdAt, feedback}',
        rationale:      'Core record of each AI generation; needed for history and analytics',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_prompt_template',
        name:           'Prompt Template',
        description:    '{id, title, template, category, isPublic}',
        rationale:      'Enables prompt library and quick-start functionality',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    integrations: [
      {
        id:             'int_ai_provider',
        name:           'AI Provider',
        description:    'OpenAI, Anthropic, or other AI API integration',
        rationale:      'The core dependency of any AI tool; without it nothing works',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'int_export',
        name:           'Export',
        description:    'Export outputs as PDF, Markdown, or plain text',
        rationale:      'Users need to use their outputs outside the app',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'int_rate_limiting',
        name:           'Rate Limiting',
        description:    'Per-user rate limits and quota tracking',
        rationale:      'Prevents abuse and manages AI API costs',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
  },

  // ── dashboard ─────────────────────────────────────────────────────────────
  dashboard: {
    keywords: ['dashboard', 'analytics', 'metrics', 'chart', 'report', 'monitor', 'kpi', 'statistics', 'data visualization', 'ops'],
    features: [
      {
        id:             'data_charts',
        name:           'Data Charts',
        description:    'Visual charts: line, bar, and pie for key metrics',
        rationale:      'The primary visualisation surface of any dashboard',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'date_range_filter',
        name:           'Date Range Filter',
        description:    'Filter all data by custom date range',
        rationale:      'Fundamental dashboard interaction; every metric needs time context',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'kpi_summary_cards',
        name:           'KPI Summary Cards',
        description:    'Top-level summary cards with trend indicators',
        rationale:      'Provides at-a-glance view; standard dashboard pattern',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'data_export',
        name:           'Data Export',
        description:    'Export data as CSV or Excel',
        rationale:      'Analysts need to work with raw data outside the dashboard',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'real_time_updates',
        name:           'Real-Time Updates',
        description:    'Live data refresh without page reload',
        rationale:      'Required for operational dashboards monitoring live systems',
        classification: 'domain_specific',
        mvpTier:        'could',
      },
      {
        id:             'custom_date_presets',
        name:           'Date Presets',
        description:    'Today, 7d, 30d, 90d quick filter buttons',
        rationale:      'Speeds up common date range selections',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
      {
        id:             'alert_thresholds',
        name:           'Alert Thresholds',
        description:    'Notify when a metric crosses a defined threshold',
        rationale:      'Proactive monitoring; reduces need to check dashboard constantly',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    flows: [
      {
        id:             'flow_view_overview',
        name:           'View Overview Flow',
        description:    'Land on dashboard → see KPI cards → scan charts → drill down',
        rationale:      'The primary usage pattern for any dashboard',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_filter_data',
        name:           'Filter Data Flow',
        description:    'Select date range → all charts update → view filtered metrics',
        rationale:      'Core interaction; dashboards are useless without filtering',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_export_report',
        name:           'Export Report Flow',
        description:    'Select data range → choose format → download report',
        rationale:      'Analysts need to share findings outside the dashboard',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    roles: [
      {
        id:             'role_analyst',
        name:           'Analyst',
        description:    'Primary user who interprets data and creates reports',
        rationale:      'Primary actor in any analytics dashboard',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'role_viewer',
        name:           'Viewer',
        description:    'Read-only access for stakeholders',
        rationale:      'Executives or clients who need to view but not edit dashboards',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    entities: [
      {
        id:             'entity_metric',
        name:           'Metric',
        description:    '{id, name, value, timestamp, category}',
        rationale:      'Core data unit displayed in charts and KPI cards',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_report',
        name:           'Report',
        description:    '{id, name, dateRange, filters, chartConfig[]}',
        rationale:      'Saved dashboard configuration for recurring reporting',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    integrations: [
      {
        id:             'int_data_source',
        name:           'Data Source',
        description:    'Connect to data via API, CSV, or database',
        rationale:      'Without a data source the dashboard has nothing to display',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'int_charting_library',
        name:           'Charting Library',
        description:    'Chart.js or D3 for rendering charts',
        rationale:      'Custom charting from scratch is impractical; a library is required',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
    ],
  },

  // ── social ────────────────────────────────────────────────────────────────
  social: {
    keywords: ['social', 'community', 'feed', 'post', 'follow', 'profile', 'network', 'share', 'comment', 'like', 'connection'],
    features: [
      {
        id:             'user_profiles',
        name:           'User Profiles',
        description:    'Public profile with bio, avatar, and stats',
        rationale:      'Identity is foundational to any social network',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'social_feed',
        name:           'Social Feed',
        description:    'Chronological or ranked feed of posts from followed users',
        rationale:      'The core content surface of any social platform',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'post_creation',
        name:           'Post Creation',
        description:    'Create posts with text, images, and links',
        rationale:      'User-generated content is the product; without it the feed is empty',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'follow_system',
        name:           'Follow System',
        description:    'Follow and unfollow users; follower/following counts',
        rationale:      'The social graph; determines what appears in each user\'s feed',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'notifications',
        name:           'Notifications',
        description:    'Notify on likes, comments, and new followers',
        rationale:      'Re-engagement mechanism; drives return visits',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'direct_messages',
        name:           'Direct Messages',
        description:    'Private 1-to-1 messaging between users',
        rationale:      'Expected in most social platforms; drives private engagement',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
      {
        id:             'content_moderation',
        name:           'Content Moderation',
        description:    'Report or flag content; basic moderation tools',
        rationale:      'Required for platform safety and regulatory compliance',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    flows: [
      {
        id:             'flow_create_post',
        name:           'Create Post Flow',
        description:    'Compose → add media → set visibility → publish',
        rationale:      'Primary content creation action; the engine of the social graph',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_discover_users',
        name:           'Discover Users Flow',
        description:    'Search or browse users → view profile → follow',
        rationale:      'Needed to grow the social graph and populate the feed',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'flow_engage_post',
        name:           'Engage with Post Flow',
        description:    'View post → like or comment → share',
        rationale:      'Core engagement loop that drives time-on-platform',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    roles: [
      {
        id:             'role_member',
        name:           'Member',
        description:    'Standard platform member who creates and consumes content',
        rationale:      'Primary actor in any social network',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'role_moderator',
        name:           'Moderator',
        description:    'Reviews flagged content and enforces community rules',
        rationale:      'Required for platform safety at any meaningful scale',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'role_admin',
        name:           'Admin',
        description:    'Full platform administration and configuration',
        rationale:      'Needed for platform operations and policy enforcement',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
    entities: [
      {
        id:             'entity_post',
        name:           'Post',
        description:    '{id, authorId, content, media[], likes[], comments[], createdAt}',
        rationale:      'Core content unit of any social platform',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_user_profile',
        name:           'User Profile',
        description:    '{id, username, bio, avatar, followersCount, followingCount}',
        rationale:      'The public identity record for each user',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'entity_notification',
        name:           'Notification',
        description:    '{id, userId, type, actorId, resourceId, read}',
        rationale:      'Drives re-engagement; required for notification features',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    integrations: [
      {
        id:             'int_image_cdn',
        name:           'Image CDN',
        description:    'Store and serve user-uploaded images at scale',
        rationale:      'User-uploaded media must be stored reliably and served fast',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'int_push_notifications',
        name:           'Push Notifications',
        description:    'Push notifications via browser or mobile',
        rationale:      'Re-engages users outside the app; improves retention',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
    ],
  },

  // ── landing_page ──────────────────────────────────────────────────────────
  landing_page: {
    keywords: ['landing', 'homepage', 'marketing', 'hero', 'cta', 'conversion', 'waitlist', 'launch', 'product page'],
    features: [
      {
        id:             'hero_section',
        name:           'Hero Section',
        description:    'Compelling headline, subheadline, and primary CTA above the fold',
        rationale:      'The first thing visitors see; determines whether they continue scrolling',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'social_proof',
        name:           'Social Proof',
        description:    'Testimonials, customer logos, and key stats',
        rationale:      'Builds trust and credibility; significantly improves conversion',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'features_benefits',
        name:           'Features & Benefits',
        description:    'Value propositions with icons and descriptions',
        rationale:      'Communicates what the product does and why it matters',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'email_capture',
        name:           'Email Capture',
        description:    'Email signup form for waitlist or newsletter',
        rationale:      'Primary conversion goal for pre-launch landing pages',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'faq_section',
        name:           'FAQ Section',
        description:    'Common questions and answers',
        rationale:      'Reduces pre-purchase objections and support requests',
        classification: 'helpful_optional',
        mvpTier:        'could',
      },
      {
        id:             'pricing_section',
        name:           'Pricing Section',
        description:    'Pricing tiers for products with paid plans',
        rationale:      'Required when the product has paid plans; drives conversion',
        classification: 'domain_specific',
        mvpTier:        'could',
      },
    ],
    flows: [
      {
        id:             'flow_visitor_conversion',
        name:           'Visitor Conversion Flow',
        description:    'Land → understand value → see social proof → click signup CTA',
        rationale:      'The entire purpose of a landing page; must be optimised end-to-end',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
      {
        id:             'flow_email_signup',
        name:           'Email Signup Flow',
        description:    'See signup form → enter email → confirm → thank you message',
        rationale:      'Primary conversion action for waitlist and newsletter landing pages',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    roles: [
      {
        id:             'role_visitor',
        name:           'Visitor',
        description:    'Anonymous visitor arriving from marketing channels',
        rationale:      'The only actor on a landing page; the audience for all content',
        classification: 'critical_missing',
        mvpTier:        'must',
      },
    ],
    entities: [
      {
        id:             'entity_email_subscriber',
        name:           'Email Subscriber',
        description:    '{id, email, source, subscribedAt}',
        rationale:      'Records waitlist or newsletter signups for follow-up',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
    integrations: [
      {
        id:             'int_email_capture_service',
        name:           'Email Capture Service',
        description:    'Mailchimp, ConvertKit, or custom email list management',
        rationale:      'Required to store and manage email signups from the landing page',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
      {
        id:             'int_analytics',
        name:           'Analytics',
        description:    'Track page views, CTA clicks, and conversion rates',
        rationale:      'Essential for measuring landing page effectiveness',
        classification: 'likely_needed',
        mvpTier:        'should',
      },
    ],
  },

  // ── generic (fallback) ────────────────────────────────────────────────────
  generic: {
    keywords:     [],
    features:     [],
    flows:        [],
    roles:        [],
    entities:     [],
    integrations: [],
  },

};

module.exports = { DOMAIN_RULES };
